spring:
  profiles:
    # dev | product
    active: dev
  datasource:
    name: ${database.dbname}
    username: ${database.username}
    password: ${database.password}
    url: jdbc:mysql://${database.host}:${database.port}/${database.dbname}?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 3600000
mybatis:
  mapper-locations:
    - classpath:com/cx/user/dao/*.xml
  type-aliases-package: com.cx.user.entity
dubbo:
  application:
    id: user-center-provider
    name: user-center-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 22386
    status: server
  registry:
    id: cx-registry
  scan:
    base-packages:
      - com.cx.user.service
      - com.cx.user.common

